[project]
name = "Identificacion de compromisos"
version = "0.1.0"
description = "Ingesta de Archivos PDF para su procesamiento y extraccion de `Compromisos Ambientales`"
authors = [
    {name = "Daniel", email = "danijose1803@gmail.com"},
]
dependencies = []
requires-python = ">=3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Habilita reglas
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]

# Ignora algunas reglas
ignore = [
    "E501",  # line length violations
]

# Mismo line-length que black
line-length = 88

# Permite fix automático para los imports
fix = true
unfixable = []

# Excluye directorios
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

# Versión de Python objetivo
target-version = "py312"

[tool.ruff.isort]
known-first-party = ["tu_proyecto"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.mccabe]
max-complexity = 10